name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name : checkout repositary
        uses : actions/checkout@v5

      - name: run a one-line script
        run: echo hello world!

      - name: run a multi-line script
        run: |
          echo add another action
          echo to build and test your project
