name: Main workflow 
on: push
env:
  docker_username: bastiang03
  docker_password: ${{ secrets.GITHUB_TOKEN }} 
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4 
      - name: Build application
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
          include-hidden-files: true
  Component-test:
      runs-on: ubuntu-latest
      needs: Docker-image
      steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Execute component test
        run: bash ci/component-test.sh
  Performance-test:
      runs-on: ubuntu-latest
      needs: Docker-image
      steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Execute performance test
        run: bash ci/performance-test.sh
      
